name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the deployment from (e.g., main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Firebase Deploy
      uses: wzieba/Firebase-Action@v2
      with:
        firebase_credentials: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        firebase_project_id: your-firebase-project-id
